language: generic
sudo: required

services:
  - mongodb
  - docker

install:
  - travis_wait 60 docker build -t inbeat .
  - docker run -d -p 8880:80 --name inbeat inbeat
  - ( cd inbeat && ./install.sh )

script:
  - ( cd inbeat/inbeat-bl && npm test)
  - docker ps | grep -q inbeat
  - ( cd tests && ./main-scenario-integration-test.sh )
